export const SalesQuery = {
  q001: "SELECT s.`Id`, DATE_FORMAT(s.`TrnDate`, '%m/%d/%Y') AS `TrnDate`, t.`Name` AS `TerminalName`, c.`Name` AS `CustomerName`, u.`Name` AS `SalesAgentName`, CONCAT(p.`Name`,t.`Name`, '-', s.`RecNumber`) AS `RecNumber`, SUM(NULLIF(sl.`Amount`,0)) AS `Amount`, col.`Id` AS `CollectionId`, s.`IsLocked`, s.`IsCancelled`, col.`ChangeAmount` FROM `sales` AS s LEFT JOIN `period` AS p ON p.`Id`=s.`PeriodId` LEFT JOIN `terminal` AS t ON t.`Id`=s.`TerminalId` LEFT JOIN `customer` AS c ON c.`Id`=s.`CustomerId` LEFT JOIN `user` AS u ON u.`Id`=s.`SalesAgent` LEFT JOIN `sales_line` AS sl ON sl.`SalesId`=s.`Id` LEFT JOIN `collection` AS col ON col.`SalesId`=s.`Id` WHERE s.`BranchId` = ? GROUP BY s.`Id`,s.`TrnDate`,s.`IsLocked` , t.`Name`, c.`Name`,u.`Name`, p.`Name`,t.`Name`, col.`Id`, s.`RecNumber`, s.`IsCancelled`, col.`ChangeAmount`",
  q002: "SELECT `Id` FROM `sales` WHERE `Id` = ?",
  q003: "SELECT * FROM `sales` WHERE `Id` = ?",
  q004: "SELECT s.`Id`, DATE_FORMAT(s.`TrnDate`, '%m/%d/%Y') AS `TrnDate`, CONCAT(p.`Name`,t.`Name`, '-', s.`RecNumber`) AS `RecNumber`, s.`CustomerId`, s.`TableId`, s.`TermId`, s.`DiscountId`, s.`TerminalId`, s.`IsReturn`, s.`IsRefund`, s.`IsCancelled`, s.`PaidAmount`, s.`CreditAmount`, s.`DebitAmount`, s.`BalanceAmount`, s.`Pax`, s.`TableStatus`, s.`Remarks`, CONCAT(p.`Name`,t.`Name`, '-', s.`RecNumber`) AS `SalesNumber`, SUM(NULLIF(sl.`Amount`,0)) AS `Amount`, c.`Name` AS `CustomersName`,col.`Id` AS `CollectionId`, u.`Name` AS `SalesAgentName` FROM `sales` AS s LEFT JOIN `user` AS u ON u.`Id`=s.`SalesAgent` LEFT JOIN `sales_line` AS sl ON sl.`SalesId` =s.`Id` LEFT JOIN `period` AS p ON p.`Id`=s.`PeriodId` LEFT JOIN `terminal` AS t ON t.`Id`=s.`TerminalId` LEFT JOIN `customer` AS c ON c.`Id`= s.`CustomerId` LEFT JOIN `collection` AS col ON col.`SalesId`=s.`Id` WHERE  s.`Id`= ? GROUP BY s.`Id`,col.`Id`, c.`Name`, s.`TrnDate`, s.`CustomerId`, s.`TableId`, s.`TermId`, s.`DiscountId`, s.`TerminalId`, s.`IsReturn`, s.`IsRefund`, s.`IsCancelled`, s.`PaidAmount`, s.`CreditAmount`, s.`DebitAmount`, s.`BalanceAmount`, s.`Pax`, s.`TableStatus`, s.`Remarks`",
  q005: "SELECT s.`Id`, DATE_FORMAT(s.`TrnDate`, '%m/%d/%Y') AS `TrnDate`, CONCAT(p.`Name`,t.`Name`, '-', s.`RecNumber`) AS `RecNumber`, s.`CustomerId`, s.`TableId`, s.`TermId`, s.`DiscountId`, s.`TerminalId`, s.`IsReturn`, s.`IsRefund`, s.`IsCancelled`, s.`PaidAmount`, s.`CreditAmount`, s.`DebitAmount`, s.`BalanceAmount`, s.`Pax`, s.`TableStatus`, s.`Remarks`, CONCAT(p.`Name`,t.`Name`, '-', s.`RecNumber`) AS `SalesNumber`, SUM(NULLIF(sl.`Amount`,0)) AS `Amount`, c.`Name` AS `CustomersName`,col.`Id` AS `CollectionId`, u.`Name` AS `SalesAgentName`, s.`IsLocked` FROM `sales` AS s LEFT JOIN `user` AS u ON u.`Id`=s.`SalesAgent` LEFT JOIN `sales_line` AS sl ON sl.`SalesId` =s.`Id` LEFT JOIN `period` AS p ON p.`Id`=s.`PeriodId` LEFT JOIN `terminal` AS t ON t.`Id`=s.`TerminalId` LEFT JOIN `customer` AS c ON c.`Id`= s.`CustomerId` LEFT JOIN `collection` AS col ON col.`SalesId`=s.`Id` WHERE  s.`RecNumber`= ? GROUP BY s.`Id`,col.`Id`, c.`Name`, s.`TrnDate`, s.`CustomerId`, s.`TableId`, s.`TermId`, s.`DiscountId`, s.`TerminalId`,s.`IsLocked`, s.`IsReturn`, s.`IsRefund`, s.`IsCancelled`, s.`PaidAmount`, s.`CreditAmount`, s.`DebitAmount`, s.`BalanceAmount`, s.`Pax`, s.`TableStatus`, s.`Remarks`",
  q006: "SELECT `Id` FROM `sales` WHERE `Id` = ? AND `IsLocked` = 1 ",
  q007: "SELECT `Id` FROM `sales` WHERE `Id` = ? AND IsLocked = false",
  q008: "",
  q009: "",
  q010: "",
};
