export enum QueryKey {
  APPOINTMENT = "appointment",
  CERTIFICATE = "certificate",
  FEEDBACK = "feedback",
  HEALTH = "health",
  HEALTH_CONDITION = "health-condition",
  INGREDIENT = "ingredient",
  MEAL = "meal",
  MEAL_PLAN = "meal-plan",
  MEAL_PLAN_LINE = "meal-plan-line",
  MEAL_PLAN_REQUEST = "meal-plan-request",
  NOTIFICATION = "notification",
  NUTRITION_FACT = "nutrition-fact",
  PAYMENT = "payment",
  PROFESSION = "profession",
  PROFESSION_RATING = "profession-rating",
  RECIPE = "recipe",
  RECILE_LINE = "recipe-line",
  REMINDER = "reminder",
  SUBSCRIPTION = "subscription",
  SUBSCRIPTION_LINE = "subscription-line",
  UNIT = "unit",
  USER = "user",
  USER_LOGS = "user-logs",
}
